// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Pause() {
  return window['go']['daemons']['Daemon']['Pause']();
}

export function Run() {
  return window['go']['daemons']['Daemon']['Run']();
}

export function Stop() {
  return window['go']['daemons']['Daemon']['Stop']();
}

export function Tick(arg1) {
  return window['go']['daemons']['Daemon']['Tick'](arg1);
}

export function Toggle() {
  return window['go']['daemons']['Daemon']['Toggle']();
}
