[settings]
class = "Chunks"
doc_group = "04-Admin"
doc_descr = "internal-use only data model detailing a single index chunk file"
doc_route = "412-chunkIndex"
attributes = ""
produced_by = "chunks"
disable_go = false

[[facets]]
name = "Stats"
store = "Stats"

[[facets]]
name = "Index"
store = "Index"

[[facets]]
name = "Blooms"
store = "Blooms"

[[facets]]
name = "Manifest"
store = "Manifest"

