[settings]
    class = "DalleDress"
    doc_group = "001-Route"
    doc_descr = "multi-facet generative art collection for DalleDress"
    doc_route = "700-dalledress"
    attributes = ""
    produced_by = "dalledress"
    disable_go = false

[[facets]]
    name = "Generator"
    store = "Generator"
    localStore = true
    viewType = "dashboard"
    actions = ["export"]
    isForm = true

[[facets]]
    name = "Series"
    store = "Series"
    localStore = true
    viewType = ""
    actions = ["export"]
    isForm = false

[[facets]]
    name = "Databases"
    store = "Databases"
    localStore = true
    viewType = ""
    actions = ["export"]
    isForm = false

[[facets]]
    name = "Events"
    store = "Logs"
    viewType = ""
    actions = ["export"]
    isForm = false

[[facets]]
    name = "Gallery"
    store = "Logs"
    viewType = ""
    actions = ["export"]
    isForm = false
