[settings]
    class = "DalleDress"
    doc_group = "001-Route"
    doc_descr = "multi-facet generative art collection for DalleDress"
    doc_route = "700-dalledress"
    attributes = ""
    produced_by = "dalledress"
    disable_go = false

[[facets]]
    name = "Generator"
    store = "dalle.DalleDress"
    actions = ["export"]
    viewType = "dashboard"
    renderer = "facet"
    isForm = true

[[facets]]
    name = "Series"
    store = "dalle.Series"
    actions = ["export"]
    viewType = ""
    isForm = false

[[facets]]
    name = "Databases"
    store = "dalle.Databases"
    actions = ["export"]
    viewType = ""
    isForm = false

[[facets]]
    name = "Events"
    store = "Logs"
    actions = ["export"]
    viewType = ""
    isForm = false

[[facets]]
    name = "Gallery"
    store = "dalle.DalleDress"
    actions = ["export"]
    viewType = "dashboard"
    renderer = "facet"
    isForm = false
