[settings]
    class = "Document"
    doc_group = "01-Document"
    doc_descr = "a document containing a list of addresses and some summary statistics"
    doc_route = "100-document"
    attributes = ""
    produced_by = "document"
    contains = ""
    cache_type = "cacheable"
    cache_by = "filename"
