[settings]
    class = "Names"
    doc_group = "01-Accounts"
    doc_descr = "an association between a human-readable name and an address used throughout TrueBlocks"
    doc_route = "109-name"
    attributes = ""
    produced_by = "names"

[[facets]]
name = "All"
store = "Names"

[[facets]]
name = "Custom"
store = "Names"
cruds = ["delete", "undelete", "remove", "update", "autoname"]

[[facets]]
name = "Prefund"
store = "Names"

[[facets]]
name = "Regular"
store = "Names"

[[facets]]
name = "Baddress"
store = "Names"