[settings]
class = "Status"
doc_group = "001-Route"
doc_descr = "data model for various status facets"
doc_route = "600-status"
attributes = ""
produced_by = "status"
disable_go = false

[[facets]]
name = "Status"
store = "Status"
viewType = "dashboard"

[[facets]]
name = "Caches"
store = "Caches"

[[facets]]
name = "Chains"
store = "Chains"

