// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCache() {
  return window['go']['names']['NamesCollection']['ClearCache']();
}

export function ClearSelectedTag(arg1) {
  return window['go']['names']['NamesCollection']['ClearSelectedTag'](arg1);
}

export function Crud(arg1, arg2) {
  return window['go']['names']['NamesCollection']['Crud'](arg1, arg2);
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['names']['NamesCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSelectedTag(arg1) {
  return window['go']['names']['NamesCollection']['GetSelectedTag'](arg1);
}

export function LoadData(arg1) {
  return window['go']['names']['NamesCollection']['LoadData'](arg1);
}

export function SetSelectedTag(arg1, arg2) {
  return window['go']['names']['NamesCollection']['SetSelectedTag'](arg1, arg2);
}
