// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {crud} from '../models';
import {base} from '../models';
import {sdk} from '../models';
import {names} from '../models';

export function Crud(arg1:types.ListKind,arg2:crud.Operation,arg3:types.Name):Promise<void>;

export function FindNameByAddress(arg1:base.Address):Promise<types.Name|boolean>;

export function GetPage(arg1:types.ListKind,arg2:number,arg3:number,arg4:sdk.SortSpec,arg5:string):Promise<names.NamesPage>;

export function LoadData(arg1:types.ListKind):Promise<void>;

export function NameFromAddress(arg1:base.Address):Promise<types.Name>;

export function NeedsUpdate(arg1:types.ListKind):Promise<boolean>;

export function Reset(arg1:types.ListKind):Promise<void>;
