// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {names} from '../models';
import {crud} from '../models';
import {types} from '../models';
import {sdk} from '../models';
import {sync} from '../models';

export function ClearCache():Promise<names.NamesCollection>;

export function Crud(arg1:crud.Operation,arg2:types.Name):Promise<void>;

export function GetPage(arg1:string,arg2:number,arg3:number,arg4:sdk.SortSpec,arg5:string):Promise<names.NamesPage>;

export function LoadData(arg1:sync.WaitGroup):Promise<void>;
