// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Crud(arg1, arg2, arg3) {
  return window['go']['names']['NamesCollection']['Crud'](arg1, arg2, arg3);
}

export function FindNameByAddress(arg1) {
  return window['go']['names']['NamesCollection']['FindNameByAddress'](arg1);
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['names']['NamesCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function LoadData(arg1) {
  return window['go']['names']['NamesCollection']['LoadData'](arg1);
}

export function NeedsUpdate(arg1) {
  return window['go']['names']['NamesCollection']['NeedsUpdate'](arg1);
}

export function Reset(arg1) {
  return window['go']['names']['NamesCollection']['Reset'](arg1);
}
