// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccumulateItem(arg1, arg2) {
  return window['go']['names']['NamesCollection']['AccumulateItem'](arg1, arg2);
}

export function Crud(arg1, arg2, arg3) {
  return window['go']['names']['NamesCollection']['Crud'](arg1, arg2, arg3);
}

export function GetCollectionName() {
  return window['go']['names']['NamesCollection']['GetCollectionName']();
}

export function GetCurrentSummary() {
  return window['go']['names']['NamesCollection']['GetCurrentSummary']();
}

export function GetNamesPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['names']['NamesCollection']['GetNamesPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['names']['NamesCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetStoreForKind(arg1) {
  return window['go']['names']['NamesCollection']['GetStoreForKind'](arg1);
}

export function GetSummary() {
  return window['go']['names']['NamesCollection']['GetSummary']();
}

export function GetSupportedKinds() {
  return window['go']['names']['NamesCollection']['GetSupportedKinds']();
}

export function LoadData(arg1) {
  return window['go']['names']['NamesCollection']['LoadData'](arg1);
}

export function NameFromAddress(arg1) {
  return window['go']['names']['NamesCollection']['NameFromAddress'](arg1);
}

export function NeedsUpdate(arg1) {
  return window['go']['names']['NamesCollection']['NeedsUpdate'](arg1);
}

export function Reset(arg1) {
  return window['go']['names']['NamesCollection']['Reset'](arg1);
}

export function ResetSummary() {
  return window['go']['names']['NamesCollection']['ResetSummary']();
}
