// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {crud} from '../models';
import {sdk} from '../models';
import {abis} from '../models';

export function ClearCache(arg1:types.ListKind):Promise<void>;

export function Crud(arg1:crud.Operation,arg2:types.Abi):Promise<void>;

export function GetPage(arg1:types.ListKind,arg2:number,arg3:number,arg4:sdk.SortSpec,arg5:string):Promise<abis.AbisPage>;

export function LoadData(arg1:types.ListKind):Promise<void>;

export function NeedsUpdate(arg1:types.ListKind):Promise<boolean>;
