// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccumulateItem(arg1, arg2) {
  return window['go']['abis']['AbisCollection']['AccumulateItem'](arg1, arg2);
}

export function Crud(arg1, arg2, arg3) {
  return window['go']['abis']['AbisCollection']['Crud'](arg1, arg2, arg3);
}

export function GetAbisPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['abis']['AbisCollection']['GetAbisPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetCollectionName() {
  return window['go']['abis']['AbisCollection']['GetCollectionName']();
}

export function GetCurrentSummary() {
  return window['go']['abis']['AbisCollection']['GetCurrentSummary']();
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['abis']['AbisCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetStoreForKind(arg1) {
  return window['go']['abis']['AbisCollection']['GetStoreForKind'](arg1);
}

export function GetSummary() {
  return window['go']['abis']['AbisCollection']['GetSummary']();
}

export function GetSupportedKinds() {
  return window['go']['abis']['AbisCollection']['GetSupportedKinds']();
}

export function LoadData(arg1) {
  return window['go']['abis']['AbisCollection']['LoadData'](arg1);
}

export function NeedsUpdate(arg1) {
  return window['go']['abis']['AbisCollection']['NeedsUpdate'](arg1);
}

export function Reset(arg1) {
  return window['go']['abis']['AbisCollection']['Reset'](arg1);
}

export function ResetSummary() {
  return window['go']['abis']['AbisCollection']['ResetSummary']();
}
