// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Crud(arg1, arg2, arg3) {
  return window['go']['abis']['AbisCollection']['Crud'](arg1, arg2, arg3);
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['abis']['AbisCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function LoadData(arg1) {
  return window['go']['abis']['AbisCollection']['LoadData'](arg1);
}

export function NeedsUpdate(arg1) {
  return window['go']['abis']['AbisCollection']['NeedsUpdate'](arg1);
}

export function Reset(arg1) {
  return window['go']['abis']['AbisCollection']['Reset'](arg1);
}
