// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sorting} from '../models';
import {types} from '../models';

export function Delete(arg1:string):Promise<void>;

export function EnsureInitialLoad():Promise<void>;

export function GetPage(arg1:string,arg2:number,arg3:number,arg4:sorting.SortDef,arg5:string):Promise<types.AbisPage>;
