// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['types']['AbisCollection']['Delete'](arg1);
}

export function EnsureInitialLoad() {
  return window['go']['types']['AbisCollection']['EnsureInitialLoad']();
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['types']['AbisCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}
