// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Date() {
  return window['go']['types']['Appearance']['Date']();
}

export function FinishUnmarshal() {
  return window['go']['types']['Appearance']['FinishUnmarshal']();
}

export function GetKey() {
  return window['go']['types']['Appearance']['GetKey']();
}

export function Model(arg1, arg2, arg3, arg4) {
  return window['go']['types']['Appearance']['Model'](arg1, arg2, arg3, arg4);
}

export function Orig() {
  return window['go']['types']['Appearance']['Orig']();
}

export function String() {
  return window['go']['types']['Appearance']['String']();
}
