// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {io} from '../models';
import {types} from '../models';

export function FinishUnmarshal():Promise<void>;

export function MarshalCache(arg1:io.Writer):Promise<void>;

export function Model(arg1:string,arg2:string,arg3:boolean,arg4:{[key: string]: any}):Promise<types.Model>;

export function String():Promise<string>;

export function UnmarshalCache(arg1:number,arg2:io.Reader):Promise<void>;
