// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetNamesPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['types']['Names']['GetNamesPage'](arg1, arg2, arg3, arg4, arg5);
}

export function LoadNames(arg1) {
  return window['go']['types']['Names']['LoadNames'](arg1);
}

export function ReloadNames() {
  return window['go']['types']['Names']['ReloadNames']();
}
