// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearSelectedTag(arg1) {
  return window['go']['types']['Names']['ClearSelectedTag'](arg1);
}

export function GetNamesPage2(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['types']['Names']['GetNamesPage2'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSelectedTag(arg1) {
  return window['go']['types']['Names']['GetSelectedTag'](arg1);
}

export function LoadNames(arg1) {
  return window['go']['types']['Names']['LoadNames'](arg1);
}

export function ReloadNames() {
  return window['go']['types']['Names']['ReloadNames']();
}

export function SetSelectedTag(arg1, arg2) {
  return window['go']['types']['Names']['SetSelectedTag'](arg1, arg2);
}
