// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sorting} from '../models';
import {types} from '../models';
import {sync} from '../models';

export function GetNamesPage(arg1:string,arg2:number,arg3:number,arg4:sorting.SortDef,arg5:string):Promise<types.NamesPage>;

export function LoadNames(arg1:sync.WaitGroup):Promise<void>;

export function ReloadNames():Promise<void>;
