// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sdk} from '../models';
import {types} from '../models';
import {sync} from '../models';

export function ClearSelectedTag(arg1:string):Promise<void>;

export function GetPage(arg1:string,arg2:number,arg3:number,arg4:sdk.SortSpec,arg5:string):Promise<types.NamesPage>;

export function GetSelectedTag(arg1:string):Promise<string>;

export function LoadNames(arg1:sync.WaitGroup):Promise<void>;

export function ReloadNames():Promise<types.NamesCollection>;

export function SetSelectedTag(arg1:string,arg2:string):Promise<void>;
