// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function FinishUnmarshal():Promise<void>;

export function Model(arg1:string,arg2:string,arg3:boolean,arg4:{[key: string]: any}):Promise<types.Model>;

export function ShallowCopy():Promise<types.SummaryManifest>;

export function String():Promise<string>;
