// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FinishUnmarshal() {
  return window['go']['types']['SummaryManifest']['FinishUnmarshal']();
}

export function Model(arg1, arg2, arg3, arg4) {
  return window['go']['types']['SummaryManifest']['Model'](arg1, arg2, arg3, arg4);
}

export function ShallowCopy() {
  return window['go']['types']['SummaryManifest']['ShallowCopy']();
}

export function String() {
  return window['go']['types']['SummaryManifest']['String']();
}
