// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FinishUnmarshal() {
  return window['go']['types']['SummaryMonitor']['FinishUnmarshal']();
}

export function MarshalCache(arg1) {
  return window['go']['types']['SummaryMonitor']['MarshalCache'](arg1);
}

export function Model(arg1, arg2, arg3, arg4) {
  return window['go']['types']['SummaryMonitor']['Model'](arg1, arg2, arg3, arg4);
}

export function ShallowCopy() {
  return window['go']['types']['SummaryMonitor']['ShallowCopy']();
}

export function String() {
  return window['go']['types']['SummaryMonitor']['String']();
}

export function Summarize() {
  return window['go']['types']['SummaryMonitor']['Summarize']();
}

export function UnmarshalCache(arg1, arg2) {
  return window['go']['types']['SummaryMonitor']['UnmarshalCache'](arg1, arg2);
}
