// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CacheLocations() {
  return window['go']['types']['Transaction']['CacheLocations']();
}

export function Date() {
  return window['go']['types']['Transaction']['Date']();
}

export function FinishUnmarshal() {
  return window['go']['types']['Transaction']['FinishUnmarshal']();
}

export function GasCost() {
  return window['go']['types']['Transaction']['GasCost']();
}

export function MarshalCache(arg1) {
  return window['go']['types']['Transaction']['MarshalCache'](arg1);
}

export function Model(arg1, arg2, arg3, arg4) {
  return window['go']['types']['Transaction']['Model'](arg1, arg2, arg3, arg4);
}

export function String() {
  return window['go']['types']['Transaction']['String']();
}

export function UnmarshalCache(arg1, arg2) {
  return window['go']['types']['Transaction']['UnmarshalCache'](arg1, arg2);
}
