// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FinishUnmarshal() {
  return window['go']['types']['TransactionEx']['FinishUnmarshal']();
}

export function MarshalCache(arg1) {
  return window['go']['types']['TransactionEx']['MarshalCache'](arg1);
}

export function Model(arg1, arg2, arg3, arg4) {
  return window['go']['types']['TransactionEx']['Model'](arg1, arg2, arg3, arg4);
}

export function String() {
  return window['go']['types']['TransactionEx']['String']();
}

export function UnmarshalCache(arg1, arg2) {
  return window['go']['types']['TransactionEx']['UnmarshalCache'](arg1, arg2);
}
