// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AccumulateItem(arg1, arg2) {
  return window['go']['contracts']['ContractsCollection']['AccumulateItem'](arg1, arg2);
}

export function GetContract(arg1, arg2) {
  return window['go']['contracts']['ContractsCollection']['GetContract'](arg1, arg2);
}

export function GetEvents(arg1, arg2) {
  return window['go']['contracts']['ContractsCollection']['GetEvents'](arg1, arg2);
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['contracts']['ContractsCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetStoreName(arg1, arg2, arg3) {
  return window['go']['contracts']['ContractsCollection']['GetStoreName'](arg1, arg2, arg3);
}

export function GetSummary() {
  return window['go']['contracts']['ContractsCollection']['GetSummary']();
}

export function GetSupportedFacets() {
  return window['go']['contracts']['ContractsCollection']['GetSupportedFacets']();
}

export function LoadData(arg1) {
  return window['go']['contracts']['ContractsCollection']['LoadData'](arg1);
}

export function NeedsUpdate(arg1) {
  return window['go']['contracts']['ContractsCollection']['NeedsUpdate'](arg1);
}

export function RefreshContract(arg1) {
  return window['go']['contracts']['ContractsCollection']['RefreshContract'](arg1);
}

export function Reset(arg1) {
  return window['go']['contracts']['ContractsCollection']['Reset'](arg1);
}

export function ResetSummary() {
  return window['go']['contracts']['ContractsCollection']['ResetSummary']();
}
