// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Notify(arg1) {
  return window['go']['servers']['Server']['Notify'](arg1);
}

export function Pause() {
  return window['go']['servers']['Server']['Pause']();
}

export function Run() {
  return window['go']['servers']['Server']['Run']();
}

export function Stop() {
  return window['go']['servers']['Server']['Stop']();
}

export function Tick() {
  return window['go']['servers']['Server']['Tick']();
}

export function Toggle() {
  return window['go']['servers']['Server']['Toggle']();
}
