// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Notify(arg1:Array<string>):Promise<void>;

export function Pause():Promise<void>;

export function Run():Promise<void>;

export function Stop():Promise<void>;

export function Tick():Promise<number>;

export function Toggle():Promise<void>;
