// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {crud} from '../models';
import {sdk} from '../models';
import {monitors} from '../models';

export function Clean(arg1:Array<string>):Promise<void>;

export function Crud(arg1:types.ListKind,arg2:crud.Operation,arg3:types.Monitor):Promise<void>;

export function GetPage(arg1:types.ListKind,arg2:number,arg3:number,arg4:sdk.SortSpec,arg5:string):Promise<monitors.MonitorsPage>;

export function LoadData(arg1:types.ListKind):Promise<void>;

export function NeedsUpdate(arg1:types.ListKind):Promise<boolean>;

export function Reset(arg1:types.ListKind):Promise<void>;
