// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Clean(arg1) {
  return window['go']['monitors']['MonitorsCollection']['Clean'](arg1);
}

export function Crud(arg1, arg2, arg3) {
  return window['go']['monitors']['MonitorsCollection']['Crud'](arg1, arg2, arg3);
}

export function GetMonitorsPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['monitors']['MonitorsCollection']['GetMonitorsPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['monitors']['MonitorsCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function LoadData(arg1) {
  return window['go']['monitors']['MonitorsCollection']['LoadData'](arg1);
}

export function NeedsUpdate(arg1) {
  return window['go']['monitors']['MonitorsCollection']['NeedsUpdate'](arg1);
}

export function Reset(arg1) {
  return window['go']['monitors']['MonitorsCollection']['Reset'](arg1);
}
