// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FilterAbisByName(arg1) {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['FilterAbisByName'](arg1);
}

export function FilterEventsByName(arg1) {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['FilterEventsByName'](arg1);
}

export function FilterFunctionsByName(arg1) {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['FilterFunctionsByName'](arg1);
}

export function GetAbiByAddress(arg1) {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['GetAbiByAddress'](arg1);
}

export function GetAllAbis() {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['GetAllAbis']();
}

export function GetAllEvents() {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['GetAllEvents']();
}

export function GetAllFunctions() {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['GetAllFunctions']();
}

export function GetDownloadedPage(arg1, arg2) {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['GetDownloadedPage'](arg1, arg2);
}

export function GetDownloadedState() {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['GetDownloadedState']();
}

export function GetEventBySignature(arg1) {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['GetEventBySignature'](arg1);
}

export function GetEventsPage(arg1, arg2) {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['GetEventsPage'](arg1, arg2);
}

export function GetEventsState() {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['GetEventsState']();
}

export function GetFunctionBySignature(arg1) {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['GetFunctionBySignature'](arg1);
}

export function GetFunctionsPage(arg1, arg2) {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['GetFunctionsPage'](arg1, arg2);
}

export function GetFunctionsState() {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['GetFunctionsState']();
}

export function GetKnownPage(arg1, arg2) {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['GetKnownPage'](arg1, arg2);
}

export function GetKnownState() {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['GetKnownState']();
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function LoadData(arg1) {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['LoadData'](arg1);
}

export function NeedsUpdate(arg1) {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['NeedsUpdate'](arg1);
}

export function Reset(arg1) {
  return window['go']['enhancedcollection']['EnhancedAbisCollection']['Reset'](arg1);
}
