// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {enhancedfacet} from '../models';
import {enhancedcollection} from '../models';

export function FilterAbisByName(arg1:string):Promise<Array<types.Abi>>;

export function FilterEventsByName(arg1:string):Promise<Array<types.Function>>;

export function FilterFunctionsByName(arg1:string):Promise<Array<types.Function>>;

export function GetAbiByAddress(arg1:string):Promise<types.Abi>;

export function GetAllAbis():Promise<Array<types.Abi>>;

export function GetAllEvents():Promise<Array<types.Function>>;

export function GetAllFunctions():Promise<Array<types.Function>>;

export function GetDownloadedPage(arg1:number,arg2:number):Promise<Array<types.Abi>>;

export function GetDownloadedState():Promise<enhancedfacet.LoadState>;

export function GetEventBySignature(arg1:string):Promise<types.Function>;

export function GetEventsPage(arg1:number,arg2:number):Promise<Array<types.Function>>;

export function GetEventsState():Promise<enhancedfacet.LoadState>;

export function GetFunctionBySignature(arg1:string):Promise<types.Function>;

export function GetFunctionsPage(arg1:number,arg2:number):Promise<Array<types.Function>>;

export function GetFunctionsState():Promise<enhancedfacet.LoadState>;

export function GetKnownPage(arg1:number,arg2:number):Promise<Array<types.Abi>>;

export function GetKnownState():Promise<enhancedfacet.LoadState>;

export function GetPage(arg1:number,arg2:number,arg3:string,arg4:string,arg5:types.ListKind):Promise<enhancedcollection.AbisPage>;

export function LoadData(arg1:types.ListKind):Promise<void>;

export function NeedsUpdate(arg1:types.ListKind):Promise<boolean>;

export function Reset(arg1:types.ListKind):Promise<void>;
