package types

import (
	"strings"

	"github.com/TrueBlocks/trueblocks-dalledress/pkg/logging"
)

type ListKind string

// Define known ListKind values as constants for Wails/typescriptify
// const (
// 	AbisDownloaded ListKind = "Downloaded"
// 	AbisKnown      ListKind = "Known"
// 	AbisFunctions  ListKind = "Functions"
// 	AbisEvents     ListKind = "Events"
// 	// If other modules define their own ListKinds (e.g., for "names"),
// 	// they should also be added here as constants if they need to be in the
// 	// TypeScript enum generated by Wails.
// )

var AllListKinds = []struct {
	Value  ListKind `json:"value"`
	TSName string   `json:"tsname"`
}{}

func RegisterKind(listKind ListKind) {
	logging.LogBackend("Registering ListKind: " + string(listKind))
	AllListKinds = append(AllListKinds, struct {
		Value  ListKind `json:"value"`
		TSName string   `json:"tsname"`
	}{
		listKind,
		strings.ToUpper(string(listKind)),
	})
}
