// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {big} from '../models';
import {common} from '../models';
import {fmt} from '../models';
import {base} from '../models';
import {driver} from '../models';

export function Big():Promise<big.Int>;

export function Bytes():Promise<Array<number>>;

export function CheckSum():Promise<string>;

export function Cmp(arg1:common.Address):Promise<number>;

export function Common():Promise<common.Address>;

export function Encoded32():Promise<string>;

export function Format(arg1:fmt.State,arg2:number):Promise<void>;

export function Hex():Promise<string>;

export function ImplementsGraphQLType(arg1:string):Promise<boolean>;

export function IsZero():Promise<boolean>;

export function MarshalText():Promise<Array<number>>;

export function Pad32():Promise<string>;

export function Prefix(arg1:number):Promise<string>;

export function Scan(arg1:any):Promise<void>;

export function SetBytes(arg1:Array<number>):Promise<void>;

export function SetCommon(arg1:common.Address):Promise<base.Address>;

export function SetHex(arg1:string):Promise<void>;

export function String():Promise<string>;

export function UnmarshalGraphQL(arg1:any):Promise<void>;

export function UnmarshalJSON(arg1:Array<number>):Promise<void>;

export function UnmarshalText(arg1:Array<number>):Promise<void>;

export function Value():Promise<driver.Value>;
