// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Big() {
  return window['go']['base']['Address']['Big']();
}

export function Bytes() {
  return window['go']['base']['Address']['Bytes']();
}

export function CheckSum() {
  return window['go']['base']['Address']['CheckSum']();
}

export function Cmp(arg1) {
  return window['go']['base']['Address']['Cmp'](arg1);
}

export function Common() {
  return window['go']['base']['Address']['Common']();
}

export function Encoded32() {
  return window['go']['base']['Address']['Encoded32']();
}

export function Format(arg1, arg2) {
  return window['go']['base']['Address']['Format'](arg1, arg2);
}

export function Hex() {
  return window['go']['base']['Address']['Hex']();
}

export function ImplementsGraphQLType(arg1) {
  return window['go']['base']['Address']['ImplementsGraphQLType'](arg1);
}

export function IsZero() {
  return window['go']['base']['Address']['IsZero']();
}

export function MarshalText() {
  return window['go']['base']['Address']['MarshalText']();
}

export function Pad32() {
  return window['go']['base']['Address']['Pad32']();
}

export function Prefix(arg1) {
  return window['go']['base']['Address']['Prefix'](arg1);
}

export function Scan(arg1) {
  return window['go']['base']['Address']['Scan'](arg1);
}

export function SetBytes(arg1) {
  return window['go']['base']['Address']['SetBytes'](arg1);
}

export function SetCommon(arg1) {
  return window['go']['base']['Address']['SetCommon'](arg1);
}

export function SetHex(arg1) {
  return window['go']['base']['Address']['SetHex'](arg1);
}

export function String() {
  return window['go']['base']['Address']['String']();
}

export function UnmarshalGraphQL(arg1) {
  return window['go']['base']['Address']['UnmarshalGraphQL'](arg1);
}

export function UnmarshalJSON(arg1) {
  return window['go']['base']['Address']['UnmarshalJSON'](arg1);
}

export function UnmarshalText(arg1) {
  return window['go']['base']['Address']['UnmarshalText'](arg1);
}

export function Value() {
  return window['go']['base']['Address']['Value']();
}
