// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {base} from '../models';
import {app} from '../models';
import {config} from '../models';
import {dalle} from '../models';
import {output} from '../models';

export function Cancel(arg1:base.Address):Promise<number|boolean>;

export function ConvertToAddress(arg1:string):Promise<base.Address|boolean>;

export function Fatal(arg1:string):Promise<void>;

export function GenerateEnhanced(arg1:string):Promise<string>;

export function GenerateImage(arg1:string):Promise<string>;

export function GetData(arg1:string):Promise<string>;

export function GetEnhanced(arg1:string):Promise<string>;

export function GetExistingAddrs():Promise<Array<string>>;

export function GetFilelist(arg1:string):Promise<Array<string>>;

export function GetFilename(arg1:string):Promise<string>;

export function GetHistoryCnt(arg1:string):Promise<number>;

export function GetHistoryPage(arg1:string,arg2:number,arg3:number):Promise<Array<app.TransactionEx>>;

export function GetJson(arg1:string):Promise<string>;

export function GetLast(arg1:string):Promise<string>;

export function GetNameTypes():Promise<Array<string>>;

export function GetNamesCnt():Promise<number>;

export function GetNamesPage(arg1:number,arg2:number):Promise<Array<app.NameEx>>;

export function GetPrompt(arg1:string):Promise<string>;

export function GetSeries(arg1:string):Promise<string>;

export function GetSession():Promise<config.Session>;

export function GetTerse(arg1:string):Promise<string>;

export function GetTitle(arg1:string):Promise<string>;

export function HandleLines():Promise<void>;

export function LoadSeries():Promise<dalle.Series>;

export function MakeDalleDress(arg1:string):Promise<dalle.DalleDress>;

export function MessageType(arg1:app.Message):Promise<string>;

export function RegisterCtx(arg1:base.Address):Promise<output.RenderCtx>;

export function ReloadDatabases():Promise<void>;

export function Save(arg1:string):Promise<boolean>;

export function SendMessage(arg1:base.Address,arg2:app.Message,arg3:any):Promise<void>;

export function SetLast(arg1:string,arg2:string):Promise<void>;

export function String():Promise<string>;
