// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {base} from '../models';
import {menu} from '../models';
import {preferences} from '../models';
import {utils} from '../models';
import {context} from '../models';
import {project} from '../models';
import {app} from '../models';
import {output} from '../models';

export function AddrToName(arg1:base.Address):Promise<string>;

export function Cancel(arg1:base.Address):Promise<number|boolean>;

export function ChangeImageStorageLocation(arg1:string):Promise<void>;

export function CheckRPCStatus():Promise<string>;

export function CloseProject(arg1:string):Promise<void>;

export function ConvertToAddress(arg1:string):Promise<base.Address|boolean>;

export function FileNew(arg1:menu.CallbackData):Promise<void>;

export function FileOpen(arg1:menu.CallbackData):Promise<void>;

export function FileQuit(arg1:menu.CallbackData):Promise<void>;

export function FileSave(arg1:menu.CallbackData):Promise<void>;

export function FileSaveAs(arg1:menu.CallbackData):Promise<void>;

export function GetAppId():Promise<preferences.Id>;

export function GetAppPreferences():Promise<preferences.AppPreferences>;

export function GetChainList():Promise<utils.ChainList>;

export function GetContext():Promise<context.Context>;

export function GetFilename():Promise<project.Project>;

export function GetImageURL(arg1:string):Promise<string>;

export function GetLastTab(arg1:string):Promise<string>;

export function GetMarkdown(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetOpenProjects():Promise<Array<Record<string, any>>>;

export function GetOrgPreferences():Promise<preferences.OrgPreferences>;

export function GetUserInfoStatus():Promise<app.UserInfoStatus>;

export function GetUserPreferences():Promise<preferences.UserPreferences>;

export function GetWizardReturn():Promise<string>;

export function IsInitialized():Promise<boolean>;

export function IsReady():Promise<boolean>;

export function Logger(arg1:string):Promise<void>;

export function RegisterCtx(arg1:base.Address):Promise<output.RenderCtx>;

export function SaveBounds(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SetAppPreferences(arg1:preferences.AppPreferences):Promise<void>;

export function SetChain(arg1:preferences.Chain):Promise<void>;

export function SetHelpCollapsed(arg1:boolean):Promise<void>;

export function SetInitialized(arg1:boolean):Promise<void>;

export function SetLastTab(arg1:string,arg2:string):Promise<void>;

export function SetLastView(arg1:string):Promise<void>;

export function SetMenuCollapsed(arg1:boolean):Promise<void>;

export function SetOrgPreferences(arg1:preferences.OrgPreferences):Promise<void>;

export function SetUserInfo(arg1:string,arg2:string):Promise<void>;

export function SetUserPreferences(arg1:preferences.UserPreferences):Promise<void>;

export function String():Promise<string>;

export function SwitchToProject(arg1:string):Promise<void>;
