// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteImage(arg1) {
  return window['go']['app']['App']['DeleteImage'](arg1);
}

export function ExportImage(arg1, arg2) {
  return window['go']['app']['App']['ExportImage'](arg1, arg2);
}

export function Generate(arg1) {
  return window['go']['app']['App']['Generate'](arg1);
}

export function GetDatabaseArchive(arg1) {
  return window['go']['app']['App']['GetDatabaseArchive'](arg1);
}

export function GetGenerationProgress(arg1, arg2) {
  return window['go']['app']['App']['GetGenerationProgress'](arg1, arg2);
}

export function GetImage(arg1) {
  return window['go']['app']['App']['GetImage'](arg1);
}

export function GetImageArtifactDataURL(arg1, arg2) {
  return window['go']['app']['App']['GetImageArtifactDataURL'](arg1, arg2);
}

export function GetImageModel() {
  return window['go']['app']['App']['GetImageModel']();
}

export function GetLastRoute() {
  return window['go']['app']['App']['GetLastRoute']();
}

export function GetPref(arg1) {
  return window['go']['app']['App']['GetPref'](arg1);
}

export function GetRuntimeInfo() {
  return window['go']['app']['App']['GetRuntimeInfo']();
}

export function GetSeries(arg1) {
  return window['go']['app']['App']['GetSeries'](arg1);
}

export function GetSidebarWidth() {
  return window['go']['app']['App']['GetSidebarWidth']();
}

export function GetTab(arg1) {
  return window['go']['app']['App']['GetTab'](arg1);
}

export function GetTableState(arg1) {
  return window['go']['app']['App']['GetTableState'](arg1);
}

export function GetWindowGeometry() {
  return window['go']['app']['App']['GetWindowGeometry']();
}

export function ListBackstyles(arg1) {
  return window['go']['app']['App']['ListBackstyles'](arg1);
}

export function ListDatabaseArchives() {
  return window['go']['app']['App']['ListDatabaseArchives']();
}

export function ListDatabaseRecords(arg1, arg2) {
  return window['go']['app']['App']['ListDatabaseRecords'](arg1, arg2);
}

export function ListImages(arg1, arg2) {
  return window['go']['app']['App']['ListImages'](arg1, arg2);
}

export function ListSeries(arg1, arg2) {
  return window['go']['app']['App']['ListSeries'](arg1, arg2);
}

export function NormalizeSeed(arg1, arg2) {
  return window['go']['app']['App']['NormalizeSeed'](arg1, arg2);
}

export function OpenImageArtifact(arg1, arg2) {
  return window['go']['app']['App']['OpenImageArtifact'](arg1, arg2);
}

export function Preview(arg1) {
  return window['go']['app']['App']['Preview'](arg1);
}

export function RegenerateImage(arg1) {
  return window['go']['app']['App']['RegenerateImage'](arg1);
}

export function RevealImageArtifact(arg1, arg2) {
  return window['go']['app']['App']['RevealImageArtifact'](arg1, arg2);
}

export function SaveSeries(arg1) {
  return window['go']['app']['App']['SaveSeries'](arg1);
}

export function SaveWindowGeometry(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveWindowGeometry'](arg1, arg2, arg3, arg4);
}

export function SetImageModel(arg1) {
  return window['go']['app']['App']['SetImageModel'](arg1);
}

export function SetLastRoute(arg1) {
  return window['go']['app']['App']['SetLastRoute'](arg1);
}

export function SetPref(arg1, arg2) {
  return window['go']['app']['App']['SetPref'](arg1, arg2);
}

export function SetSeriesHidden(arg1, arg2) {
  return window['go']['app']['App']['SetSeriesHidden'](arg1, arg2);
}

export function SetSidebarWidth(arg1) {
  return window['go']['app']['App']['SetSidebarWidth'](arg1);
}

export function SetTab(arg1, arg2) {
  return window['go']['app']['App']['SetTab'](arg1, arg2);
}

export function SetTableState(arg1, arg2) {
  return window['go']['app']['App']['SetTableState'](arg1, arg2);
}

export function ValidateDalle() {
  return window['go']['app']['App']['ValidateDalle']();
}
