// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateEnhanced(arg1) {
  return window['go']['app']['App']['GenerateEnhanced'](arg1);
}

export function GenerateImage(arg1) {
  return window['go']['app']['App']['GenerateImage'](arg1);
}

export function GetData(arg1) {
  return window['go']['app']['App']['GetData'](arg1);
}

export function GetEnhanced(arg1) {
  return window['go']['app']['App']['GetEnhanced'](arg1);
}

export function GetExistingAddrs() {
  return window['go']['app']['App']['GetExistingAddrs']();
}

export function GetFilelist() {
  return window['go']['app']['App']['GetFilelist']();
}

export function GetFilename(arg1) {
  return window['go']['app']['App']['GetFilename'](arg1);
}

export function GetJson(arg1) {
  return window['go']['app']['App']['GetJson'](arg1);
}

export function GetLastAddress() {
  return window['go']['app']['App']['GetLastAddress']();
}

export function GetLastRoute() {
  return window['go']['app']['App']['GetLastRoute']();
}

export function GetLastSeries() {
  return window['go']['app']['App']['GetLastSeries']();
}

export function GetLastTab() {
  return window['go']['app']['App']['GetLastTab']();
}

export function GetNames(arg1, arg2) {
  return window['go']['app']['App']['GetNames'](arg1, arg2);
}

export function GetNamesCnt() {
  return window['go']['app']['App']['GetNamesCnt']();
}

export function GetPrompt(arg1) {
  return window['go']['app']['App']['GetPrompt'](arg1);
}

export function GetSeries(arg1) {
  return window['go']['app']['App']['GetSeries'](arg1);
}

export function GetSession() {
  return window['go']['app']['App']['GetSession']();
}

export function GetTerse(arg1) {
  return window['go']['app']['App']['GetTerse'](arg1);
}

export function GetTitle(arg1) {
  return window['go']['app']['App']['GetTitle'](arg1);
}

export function HandleLines() {
  return window['go']['app']['App']['HandleLines']();
}

export function LoadSeries() {
  return window['go']['app']['App']['LoadSeries']();
}

export function MakeDalleDress(arg1) {
  return window['go']['app']['App']['MakeDalleDress'](arg1);
}

export function Save(arg1) {
  return window['go']['app']['App']['Save'](arg1);
}

export function SetLastAddress(arg1) {
  return window['go']['app']['App']['SetLastAddress'](arg1);
}

export function SetLastRoute(arg1) {
  return window['go']['app']['App']['SetLastRoute'](arg1);
}

export function SetLastSeries(arg1) {
  return window['go']['app']['App']['SetLastSeries'](arg1);
}

export function SetLastTab(arg1) {
  return window['go']['app']['App']['SetLastTab'](arg1);
}

export function String() {
  return window['go']['app']['App']['String']();
}
