// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['app']['App']['Cancel'](arg1);
}

export function ConvertToAddress(arg1) {
  return window['go']['app']['App']['ConvertToAddress'](arg1);
}

export function Fatal(arg1) {
  return window['go']['app']['App']['Fatal'](arg1);
}

export function GetExistingAddrs() {
  return window['go']['app']['App']['GetExistingAddrs']();
}

export function GetHistoryCnt(arg1) {
  return window['go']['app']['App']['GetHistoryCnt'](arg1);
}

export function GetHistoryPage(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetHistoryPage'](arg1, arg2, arg3);
}

export function GetLast(arg1) {
  return window['go']['app']['App']['GetLast'](arg1);
}

export function GetNameTypes() {
  return window['go']['app']['App']['GetNameTypes']();
}

export function GetNamesCnt() {
  return window['go']['app']['App']['GetNamesCnt']();
}

export function GetNamesPage(arg1, arg2) {
  return window['go']['app']['App']['GetNamesPage'](arg1, arg2);
}

export function GetServer(arg1) {
  return window['go']['app']['App']['GetServer'](arg1);
}

export function GetSession() {
  return window['go']['app']['App']['GetSession']();
}

export function RegisterCtx(arg1) {
  return window['go']['app']['App']['RegisterCtx'](arg1);
}

export function SetLast(arg1, arg2) {
  return window['go']['app']['App']['SetLast'](arg1, arg2);
}

export function StartServers() {
  return window['go']['app']['App']['StartServers']();
}

export function StateToString(arg1) {
  return window['go']['app']['App']['StateToString'](arg1);
}

export function String() {
  return window['go']['app']['App']['String']();
}

export function ToggleServer(arg1) {
  return window['go']['app']['App']['ToggleServer'](arg1);
}
