// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Crud(arg1, arg2, arg3) {
  return window['go']['chunks']['ChunksCollection']['Crud'](arg1, arg2, arg3);
}

export function GetCollectionName() {
  return window['go']['chunks']['ChunksCollection']['GetCollectionName']();
}

export function GetPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['chunks']['ChunksCollection']['GetPage'](arg1, arg2, arg3, arg4, arg5);
}

export function GetStoreForKind(arg1) {
  return window['go']['chunks']['ChunksCollection']['GetStoreForKind'](arg1);
}

export function GetSupportedKinds() {
  return window['go']['chunks']['ChunksCollection']['GetSupportedKinds']();
}

export function LoadData(arg1) {
  return window['go']['chunks']['ChunksCollection']['LoadData'](arg1);
}

export function NeedsUpdate(arg1) {
  return window['go']['chunks']['ChunksCollection']['NeedsUpdate'](arg1);
}

export function Reset(arg1) {
  return window['go']['chunks']['ChunksCollection']['Reset'](arg1);
}
