// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAddress(arg1) {
  return window['go']['project']['Project']['AddAddress'](arg1);
}

export function ClearAllFilterStates() {
  return window['go']['project']['Project']['ClearAllFilterStates']();
}

export function ClearFilterState(arg1) {
  return window['go']['project']['Project']['ClearFilterState'](arg1);
}

export function GetActiveAddress() {
  return window['go']['project']['Project']['GetActiveAddress']();
}

export function GetAddress() {
  return window['go']['project']['Project']['GetAddress']();
}

export function GetAddresses() {
  return window['go']['project']['Project']['GetAddresses']();
}

export function GetFilterState(arg1) {
  return window['go']['project']['Project']['GetFilterState'](arg1);
}

export function GetLastFacet(arg1) {
  return window['go']['project']['Project']['GetLastFacet'](arg1);
}

export function GetName() {
  return window['go']['project']['Project']['GetName']();
}

export function GetPath() {
  return window['go']['project']['Project']['GetPath']();
}

export function IsDirty() {
  return window['go']['project']['Project']['IsDirty']();
}

export function RemoveAddress(arg1) {
  return window['go']['project']['Project']['RemoveAddress'](arg1);
}

export function Save() {
  return window['go']['project']['Project']['Save']();
}

export function SaveAs(arg1) {
  return window['go']['project']['Project']['SaveAs'](arg1);
}

export function SetActiveAddress(arg1) {
  return window['go']['project']['Project']['SetActiveAddress'](arg1);
}

export function SetAddress(arg1) {
  return window['go']['project']['Project']['SetAddress'](arg1);
}

export function SetDirty(arg1) {
  return window['go']['project']['Project']['SetDirty'](arg1);
}

export function SetFilterState(arg1, arg2) {
  return window['go']['project']['Project']['SetFilterState'](arg1, arg2);
}

export function SetLastFacet(arg1, arg2) {
  return window['go']['project']['Project']['SetLastFacet'](arg1, arg2);
}

export function SetLastView(arg1) {
  return window['go']['project']['Project']['SetLastView'](arg1);
}

export function SetName(arg1) {
  return window['go']['project']['Project']['SetName'](arg1);
}
