// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {base} from '../models';

export function GetAddress():Promise<base.Address>;

export function GetName():Promise<string>;

export function GetPath():Promise<string>;

export function IsDirty():Promise<boolean>;

export function Save():Promise<void>;

export function SaveAs(arg1:string):Promise<void>;

export function SetAddress(arg1:base.Address):Promise<void>;

export function SetDirty(arg1:boolean):Promise<void>;

export function SetName(arg1:string):Promise<void>;
