// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAddress(arg1:number):Promise<string>;

export function GetDalledress(arg1:string):Promise<main.Dalledress>;

export function GetData(arg1:string):Promise<string>;

export function GetImage(arg1:string,arg2:boolean):Promise<void>;

export function GetImprovedPrompt(arg1:string):Promise<string>;

export function GetJson(arg1:string):Promise<string>;

export function GetModeration(arg1:string):Promise<string>;

export function GetPrompt(arg1:string):Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function GetTypes():Promise<Array<any>>;

export function SaveSettings():Promise<void>;
