// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Chopper(arg1:string):Promise<string>;

export function GetAddress(arg1:number):Promise<string>;

export function GetDalledress(arg1:string):Promise<main.Dalledress>;

export function GetData(arg1:string):Promise<string>;

export function GetImage(arg1:number,arg2:string):Promise<void>;

export function GetImageData(arg1:string):Promise<string>;

export function GetImprovedPrompt(arg1:string):Promise<string|string>;

export function GetJson(arg1:string):Promise<string>;

export function GetModeration(arg1:string):Promise<string>;

export function GetPrompt(arg1:string):Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function GetTerse(arg1:string):Promise<string>;

export function GetTypes():Promise<Array<any>>;

export function SaveSettings():Promise<void>;

export function SeedBuilder(arg1:string):Promise<string>;

export function String():Promise<string>;
