// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetData(arg1:string):Promise<string>;

export function GetEnhanced(arg1:string):Promise<string>;

export function GetImage(arg1:string):Promise<void>;

export function GetJson(arg1:string):Promise<string>;

export function GetPrompt(arg1:string):Promise<string>;

export function GetSettings():Promise<main.Settings>;

export function GetTerse(arg1:string):Promise<string>;

export function ReportDone(arg1:string):Promise<void>;

export function ReportOn(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SaveSettings():Promise<void>;

export function String():Promise<string>;
