// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAddress(arg1) {
  return window['go']['main']['App']['GetAddress'](arg1);
}

export function GetDalledress(arg1) {
  return window['go']['main']['App']['GetDalledress'](arg1);
}

export function GetData(arg1) {
  return window['go']['main']['App']['GetData'](arg1);
}

export function GetJson(arg1) {
  return window['go']['main']['App']['GetJson'](arg1);
}

export function GetPrompt(arg1) {
  return window['go']['main']['App']['GetPrompt'](arg1);
}
