// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetData(arg1) {
  return window['go']['main']['App']['GetData'](arg1);
}

export function GetEnhanced(arg1) {
  return window['go']['main']['App']['GetEnhanced'](arg1);
}

export function GetImage(arg1) {
  return window['go']['main']['App']['GetImage'](arg1);
}

export function GetJson(arg1) {
  return window['go']['main']['App']['GetJson'](arg1);
}

export function GetPrompt(arg1) {
  return window['go']['main']['App']['GetPrompt'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTerse(arg1) {
  return window['go']['main']['App']['GetTerse'](arg1);
}

export function ReportDone(arg1) {
  return window['go']['main']['App']['ReportDone'](arg1);
}

export function ReportOn(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReportOn'](arg1, arg2, arg3, arg4);
}

export function SaveSettings() {
  return window['go']['main']['App']['SaveSettings']();
}

export function String() {
  return window['go']['main']['App']['String']();
}
